
grafana:
  enabled: true
  prometheusUrl: http://monitoring-prometheus:9090
  lokiUrl: http://monitoring-loki-http:3100
        
loki:
  enabled: true

promtail:
  enable: true
  sa:
    create: true
    name: promtail
  cr:
    - name: promtail
      create: true
      rules:
      - apiGroups:
        - ""
        resources:
        - nodes
        - nodes/proxy
        - services
        - endpoints
        - pods
        verbs:
        - get
        - watch
        - list    
  crb:
    - name: promtail
      create: true
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: promtail
      subjects:
      - kind: ServiceAccount
        name: promtail
        namespace: monitoring
