autoscaling:
  enabled: false
replicaCount: 1
image:
  repository: stalwartlabs/mail-server
  pullPolicy: IfNotPresent
  tag: v0.10.7
serviceAccount:
  create: false
ports:
  - name: http
    containerPort: 8080
  - name: https
    containerPort: 443
  - name: smtp
    containerPort: 25
  - name: submission
    containerPort: 587
  - name: smtps
    containerPort: 465
  - name: imap
    containerPort: 143
  - name: imaps
    containerPort: 993
  - name: sieve
    containerPort: 4190
storage:
  class: local-path
  size: 10Gi
  mountPath: /opt/stalwart-mail
livenessProbe:
  httpGet:
    path: /healthz/live
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /healthz/ready
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10   