apiVersion: v2
name: grafana
description: Grafana is an UI for monitoring and visualizing data.
version: 0.0.2
appVersion: 0.0.2
dependencies:
  - name: common
    repository: https://jon-zuka.github.io/helm-charts
    version: 0.0.3
