apiVersion: v2
name: stalwart
description: Self hosted email service
version: 0.0.0-div.1
appVersion: 0.0.0-div.1
dependencies:
  - name: common
    repository: file://../../libs/common
    version: ">=0.0.0-dev.1"
