pvc:
  - name: data
    size: 10Gi
    class: local-path
    path: /opt/stalwart-mail/data
      
svc:
  - name: http
    type: ClusterIP
    ports:
      - name: http
        port: 80
        containerPort: 8080
      - name: https
        port: 443
  - name: tcp
    type: ClusterIP
    ports:
      - name: imap
        port: 143
      - name: pop
        port: 110
      - name: pops
        port: 995
      - name: smtp
        port: 25
      - name: smtpsub
        port: 587
      - name: imaps
        port: 993
      - name: smtps
        port: 465
  - name: smtp
    type: LoadBalancer
    ports:
      - name: smtp
        port: 25
 
sa:
  create: false
    
deploy:
  image:
    # -- image to use for deploying
    repository: ghcr.io/stalwartlabs/mail-server
    tag: v0.11.6
    policy: IfNotPresent
  # -- Horizontal pod scaling setup
  hpa:
    min: 1
    max: 1
    cpu: 90
    memory: 90
  # -- Resources
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "1200m"
      memory: "512Mi"
